apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: iceland
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikalabs.io
    chart: one-image
    targetRevision: 1.18.0
    helm:
      valuesObject:
        host: iceland.wo1.sikademo.com
        image: ondrejsika/iceland-2
